package com.companyname.projectname.pacakge.hibernate.persistence;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated Dec 26, 2009 1:14:45 AM by Hibernate Tools 3.2.4.GA


/**
 * Department generated by hbm2java
 */

/*
 <hibernate-mapping>
    <class name="com.companyname.projectname.pacakge.hibernate.persistence.Department" table="department">
        <id name="departmentId" type="int">
            <column name="departmentId" />
            <generator class="assigned" />
        </id>
        <property name="departmentName" >
            <column name="departmentName" not-null="true" />
        </property>

    </class>
</hibernate-mapping>
 */
@Entity
@Table(name="department")
public class Department {
	@Id
	@Column(name="departmentId")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int departmentId;
	
	@Column(name="departmentName", nullable=false)
	private String departmentName;
	
	public Department() {
	}

	public Department(int departmentId, String departmentName) {
		this.departmentId = departmentId;
		this.departmentName = departmentName;
	}

	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	
}
